// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/ptable?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/ptable?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-test: https://github.com/rdavid/ptable/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-alphanum: http://www.davekoelle.com/alphanum.html
:url-checkmake: https://github.com/checkmake/checkmake
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-hoc: https://hitsofcode.com/view/github/rdavid/ptable?branch=master
:url-license: https://github.com/rdavid/ptable/blob/master/LICENSES/0BSD.txt
:url-redo: http://cr.yp.to/redo.html
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/ptable/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Pretty Table

[subs=attributes+]
++++
<div align="right">
<a href="{url-test}"><img src="{img-test}" alt="test"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/ptable" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

This {cpp} template formats and prints tabular data.
It calculates column widths after all fields are known.
The header-only template requires a {cpp}03 compiler and the standard
library.
Copy `PrettyTable.h` and `AlphaNum.h` into a project to use it.
Column sorting uses Dirk Jagdmann's implementation of the
{url-alphanum}[alphanum algorithm] for human-friendly ordering.
The following snippet shows typical usage:

[,c++]
----
CPrettyTable<int, const char*, double> tbl("num", "name", "score");
for (int i = 0; i < 5; ++i) {
  tbl.Add(i + 1, "FooBar", 2.5 * (i + 1));
}
tbl.SetCaption("FooBar");
tbl.Dump(std::cerr);
----
The code prints the following output to the standard error stream:

ifdef::pages-build[]
++++
<div id="term-demo">
  <div class="window">
    <div class="titlebar">
      <div class="dots">
        <span class="dot red"></span>
        <span class="dot yellow"></span>
        <span class="dot green"></span>
      </div>
      <span class="tab">main.cpp &mdash; CPrettyTable demo</span>
    </div>
    <div class="term-body">
      <div class="row">
        <span class="gutter"></span>
        <span class="prompt"><span class="sym">$</span> g++ -std=c++03 -o app main.cpp &amp;&amp; ./app</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">1</span></span>
        <span class="tbl">+-----+<span class="cap">[ FooBar ]</span>------+</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">2</span></span>
        <span class="tbl">| num | name   | score |</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="tbl">+-----+--------+-------+</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">3</span></span>
        <span class="tbl">|<span class="num-cell">   1 </span>|<span class="str-cell"> FooBar </span>|<span class="num-cell">   2.5 </span>|</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="tbl">|<span class="num-cell">   2 </span>|<span class="str-cell"> FooBar </span>|<span class="num-cell">     5 </span>|</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="tbl">|<span class="num-cell">   3 </span>|<span class="str-cell"> FooBar </span>|<span class="num-cell">   7.5 </span>|</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="tbl">|<span class="num-cell">   4 </span>|<span class="str-cell"> FooBar </span>|<span class="num-cell">    10 </span>|</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="tbl">|<span class="num-cell">   5 </span>|<span class="str-cell"> FooBar </span>|<span class="num-cell">  12.5 </span>|</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">4</span></span>
        <span class="tbl">+-----+--------+-------+</span>
      </div>
    </div>
  </div>
  <div class="legend">
    <h3>What the numbers point at</h3>
    <ol>
      <li>
        <span class="num">1</span>
        <p><code>SetCaption</code> embeds its text into the first delimiter line instead of printing a separate title row.</p>
      </li>
      <li>
        <span class="num">2</span>
        <p>Column titles come straight from the constructor arguments &mdash; there's no separate header-setting call.</p>
      </li>
      <li>
        <span class="num">3</span>
        <p>Numeric types report <code>is_specialized=true</code>, so <code>CPrettyTable</code> right-aligns them automatically. Strings stay left-aligned.</p>
      </li>
      <li>
        <span class="num">4</span>
        <p>Column widths are fixed only after every row is known, so a five-character caption or a six-character name both fit without truncation.</p>
      </li>
    </ol>
  </div>
</div>
++++
endif::[]

ifndef::pages-build[]
[,sh]
----
+-----+[ FooBar ]------+
| num | name   | score |
+-----+--------+-------+
|   1 | FooBar |   2.5 |
|   2 | FooBar |     5 |
|   3 | FooBar |   7.5 |
|   4 | FooBar |    10 |
|   5 | FooBar |  12.5 |
+-----+--------+-------+
----
endif::[]

== Build

The project uses Daniel J. Bernstein's build system, {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.

== Test

`redo test` builds the debug application and compares its output with the
recorded golden file.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].

== License

`ptable` is copyrighted by {url-cv}[David Rabkin] and available under the
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>ptable by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/ptable" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/ptable/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
