// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/ptable?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/ptable?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-test: https://github.com/rdavid/ptable/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-alphanum: http://www.davekoelle.com/alphanum.html
:url-checkmake: https://github.com/checkmake/checkmake
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-hoc: https://hitsofcode.com/view/github/rdavid/ptable?branch=master
:url-license: https://github.com/rdavid/ptable/blob/master/LICENSES/0BSD.txt
:url-redo: http://cr.yp.to/redo.html
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/ptable/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Pretty Table

image:{img-test}[test,link={url-test}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

This C++ template formats and prints tabular data.
It calculates column widths after all fields are known.
The header-only template requires a C++03 compiler and the standard
library.
Copy `PrettyTable.h` and `AlphaNum.h` into a project to use it.
Column sorting uses Dirk Jagdmann's implementation of the
{url-alphanum}[alphanum algorithm] for human-friendly ordering.
The following snippet shows typical usage:

[,c++]
----
CPrettyTable<int, const char*, double> tbl("num", "name", "score");
for (int i = 0; i < 5; ++i) {
  tbl.Add(i + 1, "FooBar", 2.5 * (i + 1));
}
tbl.SetCaption("FooBar");
tbl.Dump(std::cerr);
----
The code prints the following output to the standard error stream:
[,sh]
----
+-----+[ FooBar ]------+
| num | name   | score |
+-----+--------+-------+
|   1 | FooBar |   2.5 |
|   2 | FooBar |     5 |
|   3 | FooBar |   7.5 |
|   4 | FooBar |    10 |
|   5 | FooBar |  12.5 |
+-----+--------+-------+
----

== Build

The project uses Daniel J. Bernstein's build system, {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.

== Test

`redo test` builds the debug application and compares its output with the
recorded golden file.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].

== License

`ptable` is copyrighted by {url-cv}[David Rabkin] and available under the
{url-license}[Zero-Clause BSD license].
