// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-hadolint: https://github.com/hadolint/hadolint
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSE
:url-redo: http://cr.yp.to/redo.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= PTable

image:https://github.com/rdavid/ptable/actions/workflows/codeql-analysis.yml/badge.svg[code ql,link=https://github.com/rdavid/ptable/actions/workflows/codeql-analysis.yml]
image:https://github.com/rdavid/ptable/actions/workflows/lint.yml/badge.svg[linters,link=https://github.com/rdavid/ptable/actions/workflows/lint.yml]
image:https://hitsofcode.com/github/rdavid/ptable?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/ptable?branch=master]
image:https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/ptable/blob/master/LICENSE]

toc::[]

== About

The C++ template is used to print data in a formatted table.
It calculates the proper indentations once all the fields are known.
Here is an example code snippet to demonstrate its usage:

[,c++]
----
CPrettyTable<int, const char*, double> tbl("num", "name", "score");
for (int i = 0; i < 5; ++i) {
  tbl.Add(i+1, "FooBar", 2.5*(i+1));
}
tbl.SetCaption("FooBar");
tbl.Dump(std::cerr);
----

The code prints following line to standard error stream:

[,sh]
----
+-----+[ FooBar ]------+
| num | name   | score |
+-----+--------+-------+
|   1 | FooBar |   2.5 |
|   2 | FooBar |     5 |
|   3 | FooBar |   7.5 |
|   4 | FooBar |    10 |
|   5 | FooBar |  12.5 |
+-----+--------+-------+
----

== Build

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.

== Test

`redo test` runs unit tests.
`redo lint` applies the following linters to the source files:
{url-checkmake}[`checkmake`], {url-hadolint}[`hadolint`],
{url-shellcheck}[`shellcheck`], {url-shfmt}[`shfmt`], {url-typos}[`typos`],
{url-vale}[`vale`], {url-yamllint}[`yamllint`].

== License

`ptable` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
