# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: checkmake
'on': [pull_request, push]
env:
  CM_BIN: /usr/local/bin/checkmake
  CM_URL: https://github.com/mrtazz/checkmake/releases/download/0.2.2/checkmake-0.2.2.linux.amd64 # yamllint disable-line
jobs:
  checkmake:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - run: |
          curl --location --output "$CM_BIN" --silent "$CM_URL"
          chmod +x "$CM_BIN"
          "$CM_BIN" Makefile
