---
name: linters
'on': push
env:
  CM_BIN: /usr/local/bin/checkmake
  CM_URL: https://github.com/mrtazz/checkmake/releases/download/0.2.2/checkmake-0.2.2.linux.amd64 # yamllint disable-line
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl --location --output $CM_BIN --silent $CM_URL
          chmod +x $CM_BIN
          $CM_BIN Makefile
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./*.do
      - uses: mfinelli/setup-shfmt@v2
      - run: shfmt -d *.do
      - uses: crate-ci/typos@master
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/*.yml .github/workflows/*.yml
          strict: true
